rteval: Fix incorrect import in sysinfo dir
Fix incorrect import in rteval/sysinfo/__init__.py

This could cause a traceback

 rteval --duration=60
Traceback (most recent call last):
  File "/usr/bin/rteval", line 196, in <module>
    from rteval.sysinfo import dmi
  File "/usr/lib/python3.6/site-packages/rteval/sysinfo/__init__.py", line 37, in <module>
    import rteval.sysinfo.dmi as dmi
AttributeError: module 'rteval' has no attribute 'sysinfo'

Signed-off-by: John Kacur <jkacur@redhat.com>