rteval: Parse cpuinfo correctly when model name has a colon
The function cpuinfo() splits fields in /proc/cpuinfo with a colon ':'

This can cause a
ValueError: too many values to unpack (expected 2)

This is easily fixed by setting the maximum number of splits to 1

Signed-off-by: John Kacur <jkacur@redhat.com>