rteval: Fix potential relative import error with rtevalConfig
It is possible to get a relative import error with rtevalConfig.
For example, if you are running from git without installing, you should
only need to set PYTHONPATH to the base directory.

To see the problem run

python3 rteval/rtevalConfig.py
Traceback (most recent call last):
  File "rteval/rtevalConfig.py", line 36, in <module>
    from .Log import Log
ImportError: attempted relative import with no known parent package

To fix this include the rteval dir in the import.

Signed-off-by: John Kacur <jkacur@redhat.com>